# Generated by Django 5.2.7 on 2026-05-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_tariffs(apps, schema_editor):
    TariffPlan = apps.get_model('core', 'TariffPlan')
    data = [
        {
            'slug': 'basic',
            'name': 'Базовый',
            'price': 990,
            'billing_days': 30,
            'access_all': False,
            'max_courses': 3,
            'tagline': '990 ₽ в месяц',
            'perks': 'Доступ к 3 любым курсам на ваш выбор\nУроки и тесты без ограничений в рамках выбранных курсов\nПрогресс в личном кабинете',
            'order': 1,
        },
        {
            'slug': 'premium',
            'name': 'Премиум',
            'price': 1990,
            'billing_days': 30,
            'access_all': True,
            'max_courses': None,
            'tagline': '1990 ₽ в месяц',
            'perks': 'Доступ ко всем курсам платформы\nНовые курсы сразу в подписке\nПриоритет в поддержке',
            'order': 2,
        },
        {
            'slug': 'yearly',
            'name': 'Годовой',
            'price': 9900,
            'billing_days': 365,
            'access_all': True,
            'max_courses': None,
            'tagline': '9900 ₽ в год',
            'perks': 'Все курсы на 12 месяцев\nМаксимальная экономия\nБейдж PRO в шапке сайта',
            'order': 3,
        },
    ]
    for row in data:
        row = dict(row)
        slug = row.pop('slug')
        TariffPlan.objects.update_or_create(slug=slug, defaults=row)


def unseed_tariffs(apps, schema_editor):
    TariffPlan = apps.get_model('core', 'TariffPlan')
    TariffPlan.objects.filter(slug__in=('basic', 'premium', 'yearly')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscriber_course_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(help_text='Цена в рублях за период')),
                ('billing_days', models.PositiveIntegerField(help_text='Длительность подписки в днях')),
                ('access_all', models.BooleanField(default=False, help_text='True — доступ ко всем курсам')),
                ('max_courses', models.PositiveSmallIntegerField(blank=True, help_text='Для базового тарифа: сколько курсов можно выбрать; пусто если access_all', null=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('perks', models.TextField(blank=True, help_text='По одному пункту на строку')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.tariffplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_picks', to='core.course')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_courses', to='core.usersubscription')),
            ],
            options={
                'unique_together': {('subscription', 'course')},
            },
        ),
        migrations.RunPython(seed_tariffs, unseed_tariffs),
    ]
