# Generated by Django 6.0.5 on 2026-05-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursetest',
            options={'ordering': ['order'], 'verbose_name': 'Тест курса', 'verbose_name_plural': 'Тесты курсов'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос и ответ (FAQ)', 'verbose_name_plural': 'Вопросы и ответы (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подписчик на рассылку', 'verbose_name_plural': 'Подписчики на рассылку'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='tariffplan',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-started_at'], 'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usersubscriptioncourse',
            options={'verbose_name': 'Курс в подписке', 'verbose_name_plural': 'Курсы в подписках'},
        ),
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='workstage',
            options={'ordering': ['order'], 'verbose_name': 'Этап «Как это работает»', 'verbose_name_plural': 'Этапы «Как это работает»'},
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=80, verbose_name='Длительность (текст)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум-курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='A1-A2', max_length=50, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text='Справочная цена разовой покупки курса', verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-идентификатор (slug)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание (для каталога)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Длительность, мин.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exercise_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на упражнение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.TextField(blank=True, help_text='Основное содержание: текст, списки, ссылки (на странице урока).', verbose_name='Материал урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок в курсе'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.coursetest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя в отзыве'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='access_all',
            field=models.BooleanField(default=False, help_text='Если да — без лимита по числу курсов', verbose_name='Доступ ко всем курсам'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='billing_days',
            field=models.PositiveIntegerField(help_text='Длительность подписки в днях', verbose_name='Период (дней)'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='max_courses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Для базового тарифа: сколько курсов можно выбрать; пусто, если доступ ко всем', null=True, verbose_name='Макс. число курсов'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='perks',
            field=models.TextField(blank=True, help_text='По одному пункту на строку', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='price',
            field=models.PositiveIntegerField(help_text='Цена в рублях за период', verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код (slug)'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткий слоган'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.tariffplan', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersubscriptioncourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_picks', to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='usersubscriptioncourse',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_courses', to='core.usersubscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Верных ответов'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Результат (%)'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.coursetest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='action_url',
            field=models.URLField(blank=True, verbose_name='Ссылка действия'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='stages/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='step',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер шага'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
