# Generated by Django 6.0.5 on 2026-05-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_model_verbose_ru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, verbose_name='URL-идентификатор (slug)')),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], help_text='Для стандартных групп по уровням CEFR', max_length=2, verbose_name='Уровень')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('owner', models.ForeignKey(blank=True, help_text='Пусто — стандартная группа сайта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа карточек',
                'verbose_name_plural': 'Группы карточек',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=200, verbose_name='Слово (EN)')),
                ('word_ru', models.CharField(max_length=200, verbose_name='Перевод (RU)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.flashcardgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Выучено')),
                ('learned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изучения')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.flashcard', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по карточке',
                'verbose_name_plural': 'Прогресс по карточкам',
                'ordering': ['-learned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='flashcardgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_default_flashcard_group_slug'),
        ),
        migrations.AddConstraint(
            model_name='flashcardgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='unique_user_flashcard_group_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='userflashcardprogress',
            unique_together={('user', 'flashcard')},
        ),
    ]
