# Generated by Django 6.0.5 on 2026-05-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_flashcard_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceGameTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Начальный (A1–A2)'), ('intermediate', 'Средний (B1–B2)'), ('advanced', 'Продвинутый (C1–C2)')], max_length=20, verbose_name='Уровень')),
                ('sentence_text', models.CharField(help_text='Полный текст, например: The cat is sleeping.', max_length=500, verbose_name='Предложение')),
                ('correct_order', models.JSONField(help_text='Список слов в правильном порядке, например: ["The", "cat", "is", "sleeping."]', verbose_name='Слова по порядку')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Задание «Составь предложение»',
                'verbose_name_plural': 'Задания «Составь предложение»',
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSentenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Решено')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.sentencegametask', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по предложению',
                'verbose_name_plural': 'Прогресс по предложениям',
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
