from django.urls import path

from . import course_group_views, flashcard_views, match_views, sentence_views, views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_view, name='about'),
    path('how-it-works/', views.how_it_works_view, name='how_it_works'),
    path('social/', views.social_soon_view, name='social_soon'),
    path('newsletter/', views.newsletter_signup, name='newsletter'),
    path('profile/', views.profile_view, name='profile'),
    path('courses/', views.courses_list, name='courses'),
    path('tariffs/', views.tariffs, name='tariffs'),
    path('tariffs/<slug:slug>/checkout/', views.tariff_checkout, name='tariff_checkout'),
    path('subscription/setup/', views.subscription_setup, name='subscription_setup'),
    path('subscription/group/', views.subscription_pick_group, name='subscription_pick_group'),
    path('subscription/courses/', views.subscription_pick_courses, name='subscription_pick_courses'),
    path('course-groups/create/', course_group_views.course_group_create, name='course_group_create'),
    path('course-groups/<slug:slug>/edit/', course_group_views.course_group_update, name='course_group_update'),
    path('course-groups/<slug:slug>/delete/', course_group_views.course_group_delete, name='course_group_delete'),
    path('reviews/', views.reviews_page, name='reviews'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/<slug:slug>/buy/', views.course_checkout, name='course_checkout'),
    path('courses/<slug:slug>/', views.course_detail, name='course_detail'),
    path('courses/<slug:slug>/lessons/<int:lesson_id>/', views.lesson_detail, name='lesson_detail'),
    path('courses/<slug:slug>/tests/<int:test_id>/', views.take_test, name='take_test'),
    path('courses/<slug:slug>/edit/', views.course_update, name='course_update'),
    path('courses/<slug:slug>/delete/', views.course_delete, name='course_delete'),
    path('lessons/create/', views.lesson_create, name='lesson_create'),
    path('lessons/upload-image/', views.lesson_upload_image, name='lesson_upload_image'),
    path('lessons/<int:lesson_id>/edit/', views.lesson_update, name='lesson_update'),
    path('lessons/<int:lesson_id>/delete/', views.lesson_delete, name='lesson_delete'),
    path('tests/create/', views.test_create, name='test_create'),
    path('tests/<int:test_id>/edit/', views.test_update, name='test_update'),
    path('tests/<int:test_id>/delete/', views.test_delete, name='test_delete'),
    path('questions/create/', views.question_create, name='question_create'),
    path('answers/create/', views.answer_create, name='answer_create'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_confirm, name='logout'),
    path('logout/do/', views.logout_do, name='logout_do'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users/<int:user_id>/role/', views.user_role_update, name='user_role_update'),
    path('teacher-panel/', views.teacher_panel, name='teacher_panel'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('games/flashcards/', flashcard_views.flashcards_groups, name='flashcards_groups'),
    path('games/flashcards/create/', flashcard_views.flashcards_group_create, name='flashcards_group_create'),
    path(
        'games/flashcards/my/<slug:slug>/',
        flashcard_views.flashcards_group_manage,
        name='flashcards_group_manage',
    ),
    path('games/flashcards/<slug:slug>/play/', flashcard_views.flashcards_play, name='flashcards_play'),
    path('games/flashcards/<slug:slug>/answer/', flashcard_views.flashcards_answer, name='flashcards_answer'),
    path('games/match/', match_views.match_levels, name='match_levels'),
    path('games/match/<slug:slug>/play/', match_views.match_play, name='match_play'),
    path('games/match/<slug:slug>/check/', match_views.match_check, name='match_check'),
    path('games/sentence-builder/', sentence_views.sentence_builder_levels, name='sentence_builder_levels'),
    path('games/sentence-builder/<slug:level>/play/', sentence_views.sentence_builder_play, name='sentence_builder_play'),
    path('games/sentence-builder/<slug:level>/check/', sentence_views.sentence_builder_check, name='sentence_builder_check'),
]
